### ISSUE TITLE
Incorporate Android Pre-Launch checks into CI

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1006]
Can you investigate whether the pre-launch checks can be turned into a GitHub Action?
We should know immediately when we add potentially disallowed APIs.

If this is impossible please close as such.

**Comment by kassim** [comment]
It can be. It requires uploading a build to a release track - I'm not 100% if the "internal" track works but "alpha" or "beta" definitely run the prelaunch checks.

You just need to have the CI iterate the version code as part of the action - as Google Play's release tracks don't allow you to upload a build that is the same/lower than previous.

One negative is if you run it on every commit you'll find your Google Play artifact library quite full of builds. So maybe you'll want this to be manually run instead of automatically.

**Comment by epicfaace** [comment]
@kassim is right. Additionally, it may be difficult to get results for the pre-launch checks to actually show up in CI -- as far as I know, there doesn't seem to be an API for this.

**Comment by kassim** [comment]
no API, but an email does get sent
so if a not-so-clean solution is okay, one could set up a IFTTT/Zapier config to post a Slack message or create a Github Issue in response to the pre-launch check result

**Comment by epicfaace** [comment]
I don't think that's worth the effort at the moment. It may be better to use something like firebase test lab (https://github.com/WorldHealthOrganization/app/issues/354) for android checks / coverage instead.

**Comment by advayDev1** [comment]
Agree with Ashwin.  Simplest solution that works, for now.

**Comment by kassim** [comment]
Perhaps this issue should be closed in favour of https://github.com/WorldHealthOrganization/app/issues/1038 and https://github.com/WorldHealthOrganization/app/issues/1039 then?

Or maybe a criteria of what elements of the Google Play pre-launch checks should be re-implemented?

**Comment by epicfaace** [comment]
Yeah, let's close it in favor of those two issues.
