### ISSUE TITLE
App binary size optimization

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1014]
Work to reduce the size of the Android / iOS binaries. Possible steps:
* Languages done as on demand download rather than all languages within app
* App binary analysis
* Add other suggestions here

Flutter Discussion: https://itnext.io/reducing-flutter-app-size-570db9810ebb

Should be done in conjunction with #1013 to maintain size over the long term.

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by kassim** [comment]
distributing via Android App Bundle (rather than APK) should assist with this, after uploading to Google Play it should show you the range (see https://miro.medium.com/max/1400/1*u-YsnSQsorUT0JkWnWMGww.png for example) - in addition, the Google Play console does give optimization hints after uploading

there are additional recommendations and tools listed here https://developer.android.com/topic/performance/reduce-apk-size
