### ISSUE TITLE
Use HTML instead of markdown for Protect Yourself yaml

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#1030]
See https://github.com/WorldHealthOrganization/app/pull/1022#discussion_r407800233

---
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by patniemeyer** [comment]
Related comment: https://github.com/WorldHealthOrganization/app/pull/1022#discussion_r408344312

**Comment by purpledrosophila** [comment]
Is this something I could help with? If so, where is the current text for this?

**Comment by advayDev1** [comment]
@purpledrosophila this is a code and a content change: https://github.com/WorldHealthOrganization/app/pull/1022#discussion_r407800233

**Comment by advayDev1** [comment]
I'm calling this a P0 b/c having markdown where html is supposed to be will be hard to fix later.

**Comment by patniemeyer** [comment]
@purpledrosophila Are you working on this or would you like me to take it?

**Comment by purpledrosophila** [comment]
I can handle this, can you tell me where this file is located?

**Comment by patniemeyer** [comment]
The content file is `client/flutter/assets/content_bundles/protect_yourself.en.yaml` and if you compare it with the other files in that dir you'll see how the others contain simple HTML markup instead of the Markdown style `*` bold, etc.  If you look at the TravelAdvice page you'll see some simple examples of how we incorporate the HTML as text (and in `question_index.dart` we do more elaborate HTML styling).  At some point we should coordinate our HTML usagew into one utility or component that we use everywhere, but probably not necessary for this since it's closer to the TravelAdvice usage for now.  Please feel free to ping me if you have any questions.

**Comment by purpledrosophila** [comment]
Thanks! I don't think we should need a special utility to handle all of our
HTML usage; none of the utilities on the market ensure that everything is
accessible, and we can't always rely on them to make valid HTML or CSS. Do
we have an assigned HTML/CSS development team with somebody to lead it? If
not, I would suggest we should. Also, I hope this doesn't sound like
shameless self-promotion, but if we want to create a team like that, I can
help -- I've led doc teams before. I can start with putting HTML strings in
the YAML in the meantime.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by patniemeyer** [comment]
@purpledrosophila No, sorry, that's not what I meant regarding the HTML.   I was talking about the implementation in our code where we create the HTML component and styling for the page.  We either have now or soon will have some duplication across pages that could be consolidated into a single place in the code - that's all I meant about a "utility".  Sorry for the confusion.  Regarding the actual HTML in the content files that is trivial (and I hope it remains trivial) so that we can do it easily by hand.  I guess someday we could consider making a utility for the translators to work with those files but it's totally unnecessary at the moment.

**Comment by purpledrosophila** [comment]
Thanks again! I think I'm actually a little stuck at the moment; I can't
seem to update my fork to the most recent clients folder, and I have a pull
request waiting for confirmation of some changes on it. I'll get on this as
soon as my previous pull request clears. Sorry, I didn't realize until now
that you can't make multiple forks of the same repo.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by purpledrosophila** [comment]
OK, this is updated and ready now, creating a PR now. If you want me to
update any more files in this directory, let me know.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
