### ISSUE TITLE
Add Firebase Crashlytics to IOS

### ISSUE THREAD

**Issue by britannio** [WorldHealthOrganization/app#1046]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
https://github.com/WorldHealthOrganization/app/pull/885 has code on the IOS side however crash events aren't showing up in the console for IOS, only for Android.

**Comment by kassim** [comment]
I can take care of this if it's not already done? 

Would need access to the staging Firebase to test

**Comment by britannio** [comment]
> I can take care of this if it's not already done?
> 
> Would need access to the staging Firebase to test

cc @theswerd

**Comment by advayDev1** [comment]
We see non-fatal errors from iOS, @kassim please verify and/or fix logging of fatal iOS errors (crashes) to Crashlytics.

**Comment by kassim** [comment]
so Flutter exceptions all get marked as non-fatal (fatal or not) because they don't kill the iOS process
iOS fatal exceptions were coming through but you'll see them hidden behind the dSym tab because they're obfuscated until you upload dSym files - I'll make a PR to make them show up in the future..
