### ISSUE TITLE
Endpoint Security in GCP

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1508]
Bruno's comments:

**Network Security**
- [x] Firewall, TLS and load balancer: #649

**Project Level:**
- [x] [Security Scanner](https://console.cloud.google.com/security/web-scanner/getStarted?aec=1&project=who-myhealth-staging)
- [x] Audit Logs: always on. Can't be disabled.

**Comment by borowiecth** [comment]
Open requirements / actions from Cyber Security are the following:
1. Need to configure audit logs for Production GCP and GitHub. Bruno to implement
2. The application or system owner must review the service architecture with global WHO cybersecurity team in order to implement proper network isolation/segregation as per team’s recommendation.
3. The application owner has to refer to "WHO Security Standards/Rules" in order to provide security guidance and best practices to team involved in the project (stream, milestones, etc.).
4. The application or system owner has to ensure that backup method are identified and deployed based on the required time objective. (e.g. hot/cold backup, tape backup). --> No backup system in place. Google managed services like Datastore / Firestore are known to be highly durable. Backups are still desirable due to operator error.  Bruno to implement

**Comment by brunobowden** [comment]
Working on Security Command Center setup

**Comment by brunobowden** [comment]
Moved org level security to #1772. Otherwise done.
