### ISSUE TITLE
Country selector search option 

### ISSUE THREAD

**Issue by tabassumwajid2005** [WorldHealthOrganization/app#1705]
## Summary

Country selector - impairs the user experience when I need to scroll down to select countries which are written in the end of the list.

## Desired Solution

Ideally the country selection is automatic and doesn't need to be done at all. Otherwise, there should be a search option available to so user can find the country through typing.

## Additional Context

https://prnt.sc/vcbka4

## Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by Mohit020888** [comment]
@tabassumwajid2005 - Please mention the device details and app version on which you made the observations while creating issues.

**Comment by brunobowden** [comment]
@Mohit020888 @tabassumwajid2005 - in this case, it's a universal issue on all devices, so the device info doesn't matter. When a bug or feature is specific to a system or suspected to be, that's when it matters a lot more. Much of the time, you can't tell the whether it's specific or not, so in that case it's helpful to put the information in.

That said, please drag-n-drop the screenshots in to that section rather than link, e.g. https://prnt.sc/vcbka4.

**Comment by theswerd** [comment]
#1817 Closes
