### ISSUE TITLE
Localization and Globalization

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#21]
- [ ] All strings must be translated.
- [ ] All formatting must be locale-specific.
- [ ] ~Need to choose a service for translation or~ **get authoritative translations from WHO.**
- [ ] Images should ideally not contain any text or locale-specific content.

**Comment by myire** [comment]
One potential choice:

https://github.com/wikimedia/jquery.i18n

**Comment by hspinks** [comment]
Recommend authoritative translations from WHO given the importance of providing accurate medical advice.

Also recommend against jQuery-based solutions if we can avoid. Recommend [`react-native-localize`](https://github.com/react-native-community/react-native-localize) if we stick with React Native. If we do PWA, React has a couple popular libraries in [`react-i18next`](https://github.com/i18next/react-i18next) and [`react-intl`](https://github.com/formatjs/react-intl)

**Comment by myire** [comment]
+1 to "authoritative translations from WHO given the importance of providing accurate medical advice"

**Comment by advayDev1** [comment]
Great - Decision made - no autotranslate.

**Comment by theswerd** [comment]
Can I work on this?

**Comment by viviancromwell** [comment]
There are external translation services - which I am not super familiar with, but you can give them the string XML files and they send back the translations in the language you desire.

**Comment by theswerd** [comment]
One option is https://crowdin.com, they are used in Material-UI's localizations

**Comment by SamMousa** [comment]
Does WHO even provide translations in every language? I would expect local authorities to take care of that, providing translations in every possible language seems impossible.

We could use Weblate https://weblate.org/en/ to manage the translations. It is easy to set up self-hosted, also will very likely be fine hosting it for us.
Advantage of this tool is that even if we go with WHO provided translations we provide structure so that if base texts change we get notified of translations that are possibly out of date.

**Comment by hspinks** [comment]
closing in favor of tickets addressing specific tasks
