### ISSUE TITLE
Slack invite link on ONBOARDING page is broken

### ISSUE THREAD

**Issue by jdve** [WorldHealthOrganization/app#245]
I'm interested in volunteering!  It looks like the [Slack invite link](https://join.slack.com/t/who-app/shared_invite/zt-cylowls6-Q7iQPvTAenkN_Yb9MLxVIw) on the [ONBOARDING](https://github.com/WorldHealthOrganization/app/blob/master/docs/ONBOARDING.md) page is broken.

**Comment by nightlark** [comment]
Here's an invite link: https://join.slack.com/t/who-app/shared_invite/zt-cx6ycppt-ccqPJ7ZSGy3~77gSByexJw

**Comment by nightlark** [comment]
It's odd that the original one became invalid (unless 30 days have passed since it was generated or 2000 people used it).

It might be worth having a slack admin set up https://communityinviter.com/ or https://github.com/outsideris/slack-invite-automation to make sure that the invite link doesn't expire.

**Comment by ctrimm** [comment]
Agreed with the communityinviter.com idea @nightlark. I'm opening a PR as we speak to address this across the various `.md` files.

**Comment by JasPanesar** [comment]
+1  Same issue here. 

Page: https://github.com/WorldHealthOrganization/app/blob/master/docs/ONBOARDING.md

URL: Slack: https://join.slack.com/t/who-app/shared_invite/zt-cylowls6-Q7iQPvTAenkN_Yb9MLxVIw
