### ISSUE TITLE
Turn on Snyk for both Security and License review

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#262]

**Comment by hspinks** [comment]
It looks like Snyk offers 3 related services:

* License review: only available for pro accounts - @advayDev1 is reaching out to see if we can upgrade, so I will ignore this for the moment
* Automatic PRs submitted by Snyk - proposing fix to vulnerabilities automatically that we would then review and merge as needed
* Automated tests on PRs - will fail the check if there is a `High Severity` vulnerability detected
  * Downsides: our test/CI pipeline is already cumbersome, and the config for this wouldn't be checked into the repo (it's managed in Snyk's dashboard)

My thought is I'll turn on both the automatic PRs and the automated tests for now. If either one becomes too cumbersome, then we can always turn off. Let me know if you feel strongly otherwise that one or the other should not be turned on @advayDev1 @SamMousa

**Comment by hspinks** [comment]
this is turned on now 👍

**Comment by advayDev1** [comment]
I think this is a good trade-off for now.
