### ISSUE TITLE
Selection of tech stack

### ISSUE THREAD

**Issue by pjayathissa** [WorldHealthOrganization/app#7]
In order to get started, I was wondering what tech stack we will use to develop this project. 

Was thinking React-Native. Thoughts?

**Comment by brunobowden** [comment]
@harperreed @chiuki @hspinks @nikete - please add your comments too this. We should quickly converge on which stack we use. I'm generally supportive of React-Native but I'd appreciate others commenting too.

I've already spoken with Harper and we felt comfortable making use of Google Firebase and much of Google's infrastructure. Though things will keep changing around here.

**Comment by harperreed** [comment]
I think firebase would be easiest to get started. It also lends itself to the real time data portion of the app requirements. 

Let's go ahead and get started on that.

**Comment by chiuki** [comment]
I have no experience with React-Native so I'll need to learn it with the project. I have dabbled in Flutter though.

Firebase sounds good.

**Comment by advayDev1** [comment]
React-native + firebase SGTM as well.

**Comment by advayDev1** [comment]
Also I'd suggest TS instead of JS for react-native for safety.

**Comment by brunobowden** [comment]
Any takers for Flutter? Google's mobile stack looks more modern as you'd expect from it being released recently.... it'll also streamline things to be Google top to bottom. I'm not as familiar with both systems.

On the alternative, if there's greater experience around React, then that'll help us go faster right now.

**Comment by harperreed** [comment]
Flutter is fine - but i don't think is as well know as React, which would limit the numbers of volunteers that are available. 

Let's go with react-native  and firebase.

**Comment by hspinks** [comment]
+1 for React Native from my POV for rapid dev and benefits to sharing some code across iOS and Android. Not familiar with Flutter but happy to learn

**Comment by brunobowden** [comment]
React-Native and Firebase. Decision made. Closing issue.

**Comment by epicfaace** [comment]
@brunobowden and others:

I'd like to reopen this -- I'd suggest we make a PWA and go with something like [Ionic React](https://ionicframework.com/docs/react). It's far more lightweight to build a PWA (web-first) and then adapt it for mobile than start with mobile-first (React Native) and then adapt it for web (React Native Web). I think it would also be easier to onboard developers to a plain React PWA as opposed to a React Native app. It's a lot of work to get started with React Native because you have to interface and learn the React Native components, whereas someone working on a React PWA just needs to be familiar with the React HTML components to get started.

The main advantage I see of React Native is that it's easier to integrate with native functionality or existing Android / iOS codebases. I think a web-first approach with a PWA would be more than enough for the requirements we need, as well as easier and slicker to develop with.

**Comment by myire** [comment]
I believe these choices were made too quickly and ignore major privacy issues with Firebase in particular.

This is supposed to be offline/low data usage first, optimized for mass adoption.  Device support wasnt even considered in this thread either.

**Comment by myire** [comment]
From:

https://docs.google.com/document/d/1isNMLpwI2iUY92KPwJHfY7kQnpN3oCuUl6c94J7Qmhs/edit#heading=h.u7xtg8lt787c

> Essential Features

Small app size and bandwidth usage so that it can be used throughout the world
Offline for low connectivity environments with reporting when connectivity returns
Localization of interface to practically every language in common use
Separation of data to the server, allowing customization for local areas

**Comment by hspinks** [comment]
FWIW, the only requirement that React Native doesn't hit out of the ones quoted above is the small app size. Works fine with internationalization and offline / low-data functionality. There's definitely a tradeoff when it comes to the bundle size, but it seems like potential downstream requirements will need native functionality (e.g. background location sharing, etc) that might be harder to integrate with a PWA. Of course there are other things to consider such as the personal preferences & experience of the volunteers that will be putting in the bulk of the implementation work.

I don't have a strong opinion on tech stack choice, but I do think we need some structure/ownership around decision making so that there's one person (or set of people) that can balance all of those tradeoffs. And then once decisions are made, being able to move forward with confidence given the very short timelines to launch. @brunobowden can you take lead on the engineering side, or choose someone who can?

**Comment by SamMousa** [comment]
After giving both React-Native & Ionic-React a shot I must say that the experience with Ionic was a lot smoother for me.

**Comment by epicfaace** [comment]
@SamMousa 
> After giving both React-Native & Ionic-React a shot I must say that the experience with Ionic was a lot smoother for me.

:+1: 

@hspinks 

> it seems like potential downstream requirements will need native functionality (e.g. background location sharing, etc) that might be harder to integrate with a PWA

Good point. Perhaps in that case we could still use Ionic React, but use it to publish native apps -- that way we can still use Cordova plugins to use native functionality like what you mentioned.

**Comment by SamMousa** [comment]
I have used Ionic Capacitor in my tests. Note that geo is bridged so native isn't strictly needed
