### ISSUE TITLE
Multiple quick clicks will cause click functionality to occur multiple times

### ISSUE THREAD

**Issue by Moosphan** [WorldHealthOrganization/app#714]
`**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
Here is the screenshot on my phone: 

  ![screenshot](https://user-images.githubusercontent.com/31280310/77999071-ae838480-7364-11ea-814d-cc432f1d4ad4.gif)

Maybe we can avoid this in future?

**Comment by advayDev1** [comment]
If you can debounce this, go ahead

**Comment by Moosphan** [comment]
@advayDev1 Ok, I will handle this.

**Comment by dna-f** [comment]
Hi, i'm wondering if it could be just enough to await the share call (which returns a future) on the onTap

**Comment by advayDev1** [comment]
@patniemeyer @theswerd how hard is this to fix?  what's the risk?

in some cases, our bbutton presses mutate state (permissions, opt-in/out, etc.)

**Comment by theswerd** [comment]
in any of my previous apps this hasn't been a problem, I will look into the **share** package, however if it returns a void there may be nothing we can do

**Comment by theswerd** [comment]
As the share platform opens up a platform dialog and doesn’t affect the widget hierarchy or state, there shouldn’t be any risk to any outside functionality.

**Comment by advayDev1** [comment]
@theswerd what if you click Allow Notifications or Allow Location Sharing multiple times?

**Comment by theswerd** [comment]
Update: after thinking it through there is a way to do it. I will build it out tomorrow however it may be overkill. If a person presses the allow notifications button twice the worst thing that will happen is two dialogs pop up.

There is no outside risk to any widgets or hierarchy in most cases, and within the current state of our app there are none. 

A possible problem could be that if they press the button twice, and press allow twice, it could bring them 2 pages forward rather than one. This is not a worry in our current onboarding flow as it only has 1 page after the notifications page, and no pages after the location page however something to be considered in future builds.

**Comment by theswerd** [comment]
This can be solved by adding an outside Boolean representing if a void is currently active or not.

**Comment by advayDev1** [comment]
Sounds like you are working on it.

**Comment by hspinks** [comment]
Thanks for this bug report! I'm closing this in favor of the more generalized #1219
