### ISSUE TITLE
"Why" additional text for "Protect Yourself"

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#733]
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

For the "Protect Yourself" section, it should add the "Why" text listed on the WHO website:
https://www.who.int/teams/risk-communication/Individuals-and-communities

**Comment by hspinks** [comment]
See updated design:

<img width="201" alt="Screen Shot 2020-03-31 at 4 01 47 PM" src="https://user-images.githubusercontent.com/1484366/78082906-fa382d00-7368-11ea-86b9-cff5e97f21c5.png">

**Comment by sapte91** [comment]
Can we use text from here: https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public ? All of this text is already translated on this page.

**Comment by hspinks** [comment]
Decision was made to hold off on this for v1.0 due to both design concerns (large blocks of text can take away from the primary points the screen is trying to communicate) and implementation concerns (adding a new feature after the new feature freeze for distribution). We will re-prioritize this after v1.0 launch, for now I've removed `P0` and moved to the `vNext` milestone.

**Comment by advayDev1** [comment]
Design/product question of whether this additional text will be in any UI going forward.

**Comment by davidkaneda** [comment]
Don't feel strongly
