### ISSUE TITLE
Consider pictographic prophylactic reminders

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#78]
The most basic parts of our app would ideally be usable to someone who can’t read one of our speced languages or at all (poor eyesight included), using large graphics that, on a standalone basis, represent all of the needed prophylactic steps.   The original mocks have something like that:

Each time the app starts, before you get to the more complex parts, the app would remind the user with graphics for covering coughs, washing hands, etc. on each start of the app, before you get to the more complex features.  For those persons with more bandwidth, an animated version could be used as well.

Just saving this feedback from my parents away somewhere to consider.

**Comment by viviancromwell** [comment]
@advayDev1 would WHO be okay to use CDC graphics this is my core question here.  Otherwise I would be happy to swap out.  

Your second question is a trade off in usability. I agree the first time user should go through the prophylactic reminder, but for the user has used the app before, also can access them from "Protect Myself" from usability point of view it would be very redundant to go through that again (unless there is something new).

A good compromise is to do this again when

1) outbreak in a specific region
2) new content or guideline added to the reminder
 
I will break this out for a feature to be considered in the future.

**Comment by chrishosmer** [comment]
@viviancromwell i'm here

**Comment by viviancromwell** [comment]
@advayDev1 I just got words from WHO we need to use WHO official content, so we can't use the content you mentioned which I agree better for usability.  I am closing this one now but will open a new ticket to explore new illustrations that would be better for accessibility.
