### ISSUE TITLE
Must tap twice on home screen boxes after going back

### ISSUE THREAD

**Issue by crazybob** [WorldHealthOrganization/app#803]
1. Tap “Protect Yourself”
2. Swipe back.
3. Tap “Protect Yourself”
4. Nothing happens
5. Tap “Protect Yourself”
6. It works

Same after killing app.

iPhone  Xs Max with 13.3.1, TF v0.3.0 (6)

**Comment by jamesblasco** [comment]
I think this problem only happens when you tap fast and the swipe back transition hasn't finished.

I checked and it happens it different apps I have. Probably Flutter ignores gestures while transitioning. We could dig in this more but I think it should not be a priority except if someone has an easy answer for this.

**Comment by crazybob** [comment]
I think you're right. Anything we can do?

**Comment by advayDev1** [comment]
There's a PR for debounce out

#722

**Comment by jamesblasco** [comment]
Let me dig in the CupertinoPageRoute to check it out. But I am working now on other issues.

**Comment by hspinks** [comment]
I'm going to bump this to a `P1` for now - can move back up if we knock out the other `P0`s

**Comment by brunobowden** [comment]
@crazybob @jamesblasco - I can't repro this with v0.4.0. Please reopen if you can reproduce it
