### ISSUE TITLE
Notifications logic should handle case where the user agrees but cancels the iOS dialog.

### ISSUE THREAD

**Issue by patniemeyer** [WorldHealthOrganization/app#823]
When we use the Firebase `requestNotificationPermissions` method to request permission we have to guard against the possibility that the user could (intentionally or accidentally) cancel the request.  We should decide how we wish to handle this - e.g. ask again next time?  - and implement accordingly using the OS feedback from `onIosSettingsRegistered` which gives us the actual value.

**Comment by kassim** [comment]
The easiest option is to just let it behave as it currently. One would assume if a user says "deny" on the system UI of the permission request.. they actually don't want it enabled. 

The UserPreference `NotificationsEnabled` can actually be removed for the meanwhile as it's not retrieved anywhere and once needed should instead be implemented by checking the app's state instead of a saved preference value (there's a plugin `flutter_notification_permissions` that seems to have a good implementation).

The option to enable notifications can/should be added to the Settings screen as a future feature.

**Comment by britannio** [comment]
This is the only P0 issue without a PR or assignee, have we reached a conclusion on this, I can work on copying the on-boarding options into the settings screen.

**Comment by kassim** [comment]
@britannio I'm covering it in my solution to #936 

I'll assign you to the PR which I should have ready soon
