### ISSUE TITLE
FCM no autoinit, defer until ToS Approval

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#870]
FCM tokens should be generated only when the user asks for notifications.
See for example:
https://firebase.google.com/docs/cloud-messaging/android/client#prevent-auto-init

Please verify by looking at intercepted traffic on Android and iOS.

**Comment by brunobowden** [comment]
@advayDev1 - with deference to @epicfaace, I thought it might make more sense for @patniemeyer to look at this since he'll already be looking at the other FCM issue: #874

**Comment by epicfaace** [comment]
Android: https://firebase.google.com/docs/cloud-messaging/android/client#prevent-auto-init

iOS: https://firebase.google.com/docs/cloud-messaging/ios/client#prevent_auto_initialization

**Comment by patniemeyer** [comment]
@advayDev1 @epicfaace @cbgrey The docs sound like the same Firebase token is used for both analytics and messaging...  If that is the case then it seems that we can only either enable this or disable it for both.

**Comment by epicfaace** [comment]
Summarizing my chat with @patniemeyer -- we should not defer FCM autoinit until after the notifications approval. This is because the FCM token is also used for analytics, so we would want FCM autoinit to be enabled once someone passes the ToS screen, regardless of whether the user approves notifications.

This should be fine, because even though the FCM token is generated after the user passes the ToS screen (so that analytics can work), the FCM token is only sent to our server (and the phone is  thus able to receive notifications) **_only after_** the user approves notifications.

**Comment by patniemeyer** [comment]
I believe this is complete as addressed by #897.  There is some discussion about how we can definitively test on Android but I think we have taken reasonable steps to validate that what we are doing is correct and we should not let this block P0.  (We can follow up with more investigation if needed).
