### ISSUE TITLE
Travel Advice text doesn't respect accessibility font resizing

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#942]
Accessibility Audit via @avkvirtru 

The HTML-backed text (rendered using [`flutter_html`](https://pub.dev/packages/flutter_html)) in the red background on the Travel Advice screen does not respect font resizing for accessibility. Look into whether text rendered with `flutter_html` can support adapting font resizing based on accessibility settings.

---
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by britannio** [comment]
It has a `useRichText` parameter that defaults to true. Setting it to false fixes the issue as unfortunately, Flutter's RichText widget uses the constant `1.0` for its textScaleFactor instead of `MediaQuery.textScaleFactorOf`. The caveat is that the text moves to a new line whenever the text style changes. Screenshots below.

`useRichText: true`, doesn't respect accessibility font size.
![Screenshot_20200408-000030](https://user-images.githubusercontent.com/33752528/78727381-6cda7700-792c-11ea-9d46-f583b7fdbec4.jpg)

`useRichText:false`, does respect accessibility font size.
![Screenshot_20200408-000040](https://user-images.githubusercontent.com/33752528/78727389-74018500-792c-11ea-91ea-2a14a0d95959.jpg)

**Comment by britannio** [comment]
We could try a different approach or I could fork the flutter_html package, add a `textScaleFactor` and use it here to fix the issue.

**Comment by britannio** [comment]
Actually, simpler fix, for now, would be multiplying the text size by `MediaQuery.textScaleFactorOf`

**Comment by daohoangson** [comment]
I would suggest a different package for html rendering: [flutter_widget_from_html_core](https://pub.dev/packages/flutter_widget_from_html_core) which handles this kind of thing correctly.

The flutter_html package also has trouble with white spaces etc., the author has move on from the current version (0.11.x) and rewrite the html parser in [a new version (1.x)](https://pub.dev/packages/flutter_html/versions/1.0.0-pre.1) but:

1. v1.x is still pre-release
2. It pulls in a lot of dependencies like chewie for video playback, webview for iframe support, etc.

Disclaimer: I develop the flutter_widget_from_html package.

**Comment by avkvirtru** [comment]
Does this text have to be rendered as HTML to begin with?

**Comment by britannio** [comment]
> Does this text have to be rendered as HTML to begin with?

Nope but for styled text that can easily be localised we need some form of markup language to express the text and styling in and HTML seems to do the job. We could use markdown, xml, etc if we wanted.

**Comment by avkvirtru** [comment]
In this case, it's just two highlights in bold. How crucial is that bold? White text on a red background that's natively resizable would suffice, imo.

**Comment by britannio** [comment]
> In this case, it's just two highlights in bold. How crucial is that bold? White text on a red background that's natively resizable would suffice, imo.

I've fixed(ish) the issue already, just waiting for the pr to be merged
