### ISSUE TITLE
Make every text field dynamically updateable

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#981]
Except the menu.

**Comment by advayDev1** [comment]
Highest priority is the text on Protect Yourself and then Travel Advice

**Comment by advayDev1** [comment]
@patniemeyer is this done?

**Comment by patniemeyer** [comment]
I think we need to discuss - Do we really mean to move all text out of the ARB files and into content bundles?  Currently we have a distinction between dynamic "content" in the bundles and relatively static features (button titles, page titles, etc.) in the ARBs.  The latter seem, of necessity, more closely tied to the code structure and the i18n tools allow us to generate a static API for them, enforcing that.   It also speeds up development because we have built-in support in the IDE for extracting strings to the ARB files.  I'm having a hard time imagining a situation where we'd need to change, e.g. a button title so quickly that we'd have to do it sooner than we could do it with an app update (which is probably a 1 day turnaround for an app like ours).   I'm not sure that this would be a good balance for us.
