### ISSUE TITLE
Use default iOS variant-specific fonts

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#994]
After the correct fonts and theme classes are used, ensure the letter spacing overrides are removed.

cc @davidkaneda

**Comment by advayDev1** [comment]
What’s the status here @britannio ?  it’s been assigned for quite some time

**Comment by britannio** [comment]
> What’s the status here @britannio ?  it’s been assigned for quite some time

I'll look into it today or un-assign it if not.

**Comment by britannio** [comment]
Ideally, the designers would adhere to the standard defined [here](https://material.io/design/typography/) for text styling if we want to rely on Flutter's `Theme` class as that's what it's based on. The only caveat to that is that since the last stable Flutter release, the standard was updated so the new standard is only available in Flutter's beta branch and lower.

My suggestion would be to create our own basic typography system that maps to the latest Material Design spec(to support components with hardcoded themes) but also contains additional styles where necessary. Instead of using `Theme.of(context).textTheme.title` we'd use something like `PlatformTextTheme.of(context).title`

**Comment by davidkaneda** [comment]
We generally have that in the Figma file, we just don't use all styles as it's not necessary for now: 

<img width="749" alt="image" src="https://user-images.githubusercontent.com/21713/79790881-4a1f6980-8301-11ea-9b8d-f9543306dd00.png">

I'm sure there are plenty of spots where we'll need some small custom tweaking, but this is what's mostly used throughout Figma.

**Comment by britannio** [comment]
Platform default typography definitions are found here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/typography.dart#L343

The default font family is Roboto for Android and a combination of SF UI Display and SF UI Text for IOS,

SF Pro is downloadable from Apple's website and I'd expect the file to contain a license but the file is in .dmg format so I'll leave that to a mac user to investigate. https://developer.apple.com/fonts/

From searching the Flutter repo via https://cs.opensource.google/flutter and messing with the `Typography` class I suspect that the platform default fonts aren't packed into Flutter so if we want to use a single font, it's best to copy that font file into the app itself.

**Comment by davidkaneda** [comment]
Not sure if Flutter behaves differently, but those fonts should all be on the devices, so I don't think we'd need to bundle. And yes, sorry, I should have been more specific: Please replace all fonts in the above screenshot with Roboto for Android.

**Comment by britannio** [comment]
> Not sure if Flutter behaves differently, but those fonts should all be on the devices, so I don't think we'd need to bundle. And yes, sorry, I should have been more specific: Please replace all fonts in the above screenshot with Roboto for Android.
If that's the case for IOS then someone just needs to determine what the system font family name for SF Pro is then we can start using it on IOS.

**Comment by davidkaneda** [comment]
Oy, sorry, didn't realize the difference was because of the "Pro" — We could try ".SF Pro Display", or just default to ".SF UI Display" as it shows in the default styles. More important is just that we use "Display" for larger type and "Text" for smaller.
